name: django workflow
on:
  push:
    branches: ["jovita"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
       uses: actions/checkout@v2 
    - name: Set up Python 11
       uses: actions/setup-python@v4
       with:
         python-version: '11'

      - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt

      